import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";


const Home: NextPage = () => {
  useEffect(() => {
    const script = document.createElement("script");
    script.src = "/static/script.js";
    script.async = true;
    document.body.appendChild(script);
  });
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div id="unity-container" className="unity-desktop">
          <canvas id="unity-canvas" width="960" height="600"></canvas>
          <div id="unity-loading-bar">
            <div id="unity-logo"></div>
            <div id="unity-progress-bar-empty">
              <div id="unity-progress-bar-full"></div>
            </div>
          </div>
          <div id="unity-warning"> </div>
          <div id="unity-footer">
            <div id="unity-webgl-logo"></div>
            <div id="unity-fullscreen-button"></div>
            <div id="unity-build-title">NavLead</div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
